name: codacy-coverage-reporter

on:
  push:
    branches: [ master ]
  pull_request:	 
    branches: [ master ]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: dep resolve
        run: mvn dependency:resolve
      - name: test
        run: mvn clean test
      - name: cobertura check
        run: mvn cobertura:check
      - name: cobertura check
        run: mvn cobertura:cobertura
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/site/cobertura/coverage.xml
