name: codacy-coverage-reporter

on:
  push:
    branches: [ master ]
  pull_request:	 
    branches: [ master ]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: dep resolve
        run: mvn dependency:resolve
      - name: test
        run: mvn clean test
      - name: cobertura
        run: mvn cobertura:check
